services:
  - type: web
    name: labelforce-backend
    env: docker
    repo: https://github.com/reynhard0516/LabelForce1
    branch: main
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: labelforce-db
          property: connectionString
      - key: REDIS_URL
        value: redis://rediscache:6379/0

  - type: web
    name: labelforce-frontend
    env: docker
    repo: https://github.com/reynhard0516/LabelForce1
    branch: main
    dockerfilePath: frontend/Dockerfile

  - type: redis
    name: rediscache
    ipAllowList: []
    plan: free

databases:
  - name: labelforce-db
    region: oregon
    databaseName: labelforce
    user: labelforce_user
    plan: starter
