services:
  - type: web
    name: labelforce-backend
    env: docker
    repo: https://github.com/reynhard0516-commits/LabelForce1
    branch: LabelForce1
    dockerfilePath: Backend/Dockerfile   # ‚Üê FIXED
    envVars:
      - key: DATABASE_URL
        fromDataase:
          name: Labelforce-db
          property: connectionString
      - key: LF_SECRET
        value: change_me_secret

  - type: web
  name: Labelforce-Frontend
  env: docker
  repo: https://github.com/reynhard0516-commits/LabelForce1
  branch: LabelForce1
  rootDir: Frontend
  dockerfilePath: Frontend/Dockerfile

  - type: redis
    name: rediscache
    plan: free

databases:
  - name: Labelforce-db
    region: oregon
    databaseName: Labelforce
    user: Labelforce_user
    plan: basic-256mb

envVars:
  - key: VITE_API_URL
    value: https://labelforce1-8.onrender.com
