services:
  - type: web
    name: labelforce-frontend
    runtime: node
    rootDir: src
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        sync: false
